// Generated by Wrangler on Wed Jul 24 2024 18:58:26 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	__NEXT_ON_PAGES__KV_SUSPENSE_CACHE: KVNamespace;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	CLOUDFLARE_D1_DATABASE_ID: string;
	DB: D1Database;
}
