#:schema node_modules/wrangler/config-schema.json
name = "turbolink"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "__NEXT_ON_PAGES__KV_SUSPENSE_CACHE"
id = "ced2cc8212114448931c813af31efefb"

[[d1_databases]]
binding = "DB"
database_name = "prod-turbolink-d1"
database_id = "3578bc5e-8595-4a95-af6e-2d8d09099721"
